-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Category"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    "parentId" text COLLATE pg_catalog."default",
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    CONSTRAINT "Category_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."CategoryOnProducts"
(
    "productId" text COLLATE pg_catalog."default" NOT NULL,
    "categoryId" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "CategoryOnProducts_pkey" PRIMARY KEY ("productId", "categoryId")
);

CREATE TABLE IF NOT EXISTS public."Order"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    "orderNumber" text COLLATE pg_catalog."default" NOT NULL,
    "userId" text COLLATE pg_catalog."default" NOT NULL,
    status "OrderStatus" NOT NULL DEFAULT 'PENDING'::"OrderStatus",
    subtotal numeric(10, 2) NOT NULL,
    discount numeric(10, 2) NOT NULL DEFAULT 0.00,
    shipping numeric(10, 2) NOT NULL DEFAULT 0.00,
    total numeric(10, 2) NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    CONSTRAINT "Order_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."OrderItem"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    "orderId" text COLLATE pg_catalog."default" NOT NULL,
    "productId" text COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL,
    "unitPrice" numeric(10, 2) NOT NULL,
    "productName" text COLLATE pg_catalog."default" NOT NULL,
    sku text COLLATE pg_catalog."default" NOT NULL,
    subtotal numeric(10, 2) NOT NULL,
    CONSTRAINT "OrderItem_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Payment"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    "orderId" text COLLATE pg_catalog."default" NOT NULL,
    provider "PaymentProvider" NOT NULL,
    "transactionId" text COLLATE pg_catalog."default",
    amount numeric(10, 2) NOT NULL,
    status "PaymentStatus" NOT NULL DEFAULT 'PENDING'::"PaymentStatus",
    "paidAt" timestamp(3) without time zone,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    CONSTRAINT "Payment_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Product"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    sku text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    status product_status_enum NOT NULL DEFAULT 'ACTIVE'::product_status_enum,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    price numeric(10, 2) NOT NULL,
    CONSTRAINT "Product_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Stock"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL DEFAULT 0,
    "productId" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Stock_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."User"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    username text COLLATE pg_catalog."default" NOT NULL,
    "firstName" text COLLATE pg_catalog."default" NOT NULL,
    "lastName" text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    role user_roles_enum NOT NULL DEFAULT 'USER'::user_roles_enum,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    CONSTRAINT "User_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public._prisma_migrations
(
    id character varying(36) COLLATE pg_catalog."default" NOT NULL,
    checksum character varying(64) COLLATE pg_catalog."default" NOT NULL,
    finished_at timestamp with time zone,
    migration_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    logs text COLLATE pg_catalog."default",
    rolled_back_at timestamp with time zone,
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    applied_steps_count integer NOT NULL DEFAULT 0,
    CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Category"
    ADD CONSTRAINT "Category_parentId_fkey" FOREIGN KEY ("parentId")
    REFERENCES public."Category" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "Category_parentId_idx"
    ON public."Category"("parentId");


ALTER TABLE IF EXISTS public."CategoryOnProducts"
    ADD CONSTRAINT "CategoryOnProducts_categoryId_fkey" FOREIGN KEY ("categoryId")
    REFERENCES public."Category" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "CategoryOnProducts_categoryId_idx"
    ON public."CategoryOnProducts"("categoryId");


ALTER TABLE IF EXISTS public."CategoryOnProducts"
    ADD CONSTRAINT "CategoryOnProducts_productId_fkey" FOREIGN KEY ("productId")
    REFERENCES public."Product" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Order"
    ADD CONSTRAINT "Order_userId_fkey" FOREIGN KEY ("userId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."OrderItem"
    ADD CONSTRAINT "OrderItem_orderId_fkey" FOREIGN KEY ("orderId")
    REFERENCES public."Order" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "OrderItem_orderId_idx"
    ON public."OrderItem"("orderId");


ALTER TABLE IF EXISTS public."OrderItem"
    ADD CONSTRAINT "OrderItem_productId_fkey" FOREIGN KEY ("productId")
    REFERENCES public."Product" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Payment"
    ADD CONSTRAINT "Payment_orderId_fkey" FOREIGN KEY ("orderId")
    REFERENCES public."Order" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "Payment_orderId_key"
    ON public."Payment"("orderId");


ALTER TABLE IF EXISTS public."Stock"
    ADD CONSTRAINT "Stock_productId_fkey" FOREIGN KEY ("productId")
    REFERENCES public."Product" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "Stock_productId_key"
    ON public."Stock"("productId");

END;